@startuml
!theme amiga

package shared {
    interface Output {
        statusCode: number;
        body: string;
    }
}
package logging {
    class Logging {
        + message: string
        + constructor(client: LoggingClient)
        + send(): void
        - output(): Output
    }
    interface LoggingClient {
        + send(): void
    }
    class CloudWatch implements LoggingClient {
        + send(): void
    }
    Logging <.. LoggingClient
    Logging <- Output
}
@enduml