@startuml
'!theme amiga

package shared {
    interface Output {
        statusCode: number;
        body: string;
    }
}
package logging {
    class Logging {
        + message: string
        + constructor(client: LoggingClient, message: string)
        + send(): Output
    }
    interface LoggingClient {
        + send(events: LogEvent[])
    }
    class CloudWatch implements LoggingClient {
        - events: InputLogEvent[]
        + constructor(events: InputLogEvent[])
        + send(events: LogEvent[])
    }
    Logging <.. LoggingClient
    Logging <- Output
}
@enduml