service: dunderly

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  environment: ${file(serverless/provider/environment.yml)}
  iam: ${file(serverless/provider/iam.yml)}
  logRetentionInDays: 90
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256

plugins:
  - serverless-plugin-typescript

functions:
  logging: ${file(serverless/functions/logging.yml)}