name: ESLint

on:
  push:
    branches:
      - develop
  pull_request:
    paths:
      - '**.js'
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run ESLint
        run: npx eslint ./logging